name: (Draft) Jupyter Notebooks CI
on: workflow_dispatch
jobs:
  Check-Notebooks:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: check out repository code
        uses: actions/checkout@v3
      - name: set up conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          auto-activate-base: false
          activate-environment: notebook-env
          python-version: 3.10.6
      - name: Install tobac dependencies
        run: |
          conda install -c conda-forge --yes ffmpeg gcc jupyter
          conda install -c conda-forge --yes --file conda-requirements.txt
      - name: Install tobac
        run: |
          pip install .
      - name: Find all notebook files
        run: |
          find . -type f -name '*.ipynb' > nbfiles.txt
          cat nbfiles.txt
      - name: Execute all notebook files
        run: |
          while IFS= read -r nbpath; do
            jupyter nbconvert --inplace --ClearMetadataPreprocessor.enabled=True --clear-output $nbpath
            jupyter nbconvert --to notebook --inplace --execute $nbpath || true
          done < nbfiles.txt