name: Check Python File Formatting with Black
on: [push, pull_request]
jobs:
  formatting_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          miniforge-variant: miniforge
          channel-priority: strict
          channels: conda-forge
          show-channel-urls: true
          use-only-tar-bz2: true

      - name: Install dependencies and check formatting
        shell: bash -l {0}
        run:
          mamba install --quiet --yes --file requirements.txt black &&
          black --version &&
          black tobac --check --diff 
