name: Check Python File Formatting with Black
on: [push, pull_request]
jobs:
  formatting_job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up conda
        uses: mamba-org/setup-micromamba@v1

      - name: Install dependencies and check formatting
        shell: micromamba-shell {0}
        run:
          mamba install --quiet --yes --file requirements.txt black &&
          black --version &&
          black tobac --check --diff 
