name: Generate Jupyter Notebooks
on:
  pull_request:
    types:
      - closed
  workflow_dispatch:
jobs:
  Generate-Notebooks:
    if: (github.event.pull_request.merged == true) || (github.event_name == 'workflow_dispatch')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: check out repository code
        uses: actions/checkout@v3
      - name: set up conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          auto-activate-base: false
          activate-environment: notebook-env
          python-version: 3.10.6
      - name: Install tobac dependencies
        run: |
          conda install -c conda-forge --yes ffmpeg gcc jupyter
          conda install -c conda-forge --yes --file requirements.txt
      - name: Install tobac
        run: |
          pip install .
      - name: Find all notebook files
        run: |
          find . -type f -name '*.ipynb' > nbfiles.txt
          cat nbfiles.txt
      - name: Execute all notebook files
        run: |
          while IFS= read -r nbpath; do
            jupyter nbconvert --inplace --ClearMetadataPreprocessor.enabled=True --clear-output $nbpath
            jupyter nbconvert --to notebook --inplace --execute $nbpath
          done < nbfiles.txt
      - name: Commit changed notebooks
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          find . -type f -name "*.ipynb" -exec git add {} +
          git commit -m "Generated Notebooks"
          git push