name: Linting
on:
  pull-request:
    branches:
      - 'main'
      - 'RC_*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'
      - name: Install tobac
        run: pip install .
      - name: Lint with pylint
        id: pylint-output
        # omit conventions, for minimum score use: --fail-under=
        run: |
          pip install pylint
          pylint tobac --disable=C --exit-zero
          OUTPUT=$(pylint tobac --disable=C | tail -n 3)
          #OUTPUT=$(shell command or script to extract the part of the output that we wanna post as comment)
          # define random delimiter for multiline string
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "MESSAGE<<$EOF" >> "$GITHUB_ENV"
          echo "$OUTPUT" >> "$GITHUB_ENV"
          echo "$EOF" >> "$GITHUB_ENV"
      - name: Post result to PR
        uses: mshick/add-pr-comment@v1
        with:
          message: ${{ env.MESSAGE }} 
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: 'github-actions[bot]' # The user.login for temporary GitHub token
          allow-repeats: false # This is the default
